{{- if .Values.secret.s3.enabled }}
# S3 Storage credentials via External Secrets
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "supabase.secret.s3" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "supabase.labels" . | nindent 4 }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretsmanager
    kind: ClusterSecretStore
  target:
    name: {{ include "supabase.secret.s3" . }}
    creationPolicy: Owner
  data:
    - secretKey: keyId
      remoteRef:
        key: supabase/s3
        property: access_key_id  # Not used with IRSA but required by chart
    - secretKey: accessKey
      remoteRef:
        key: supabase/s3
        property: secret_access_key  # Not used with IRSA but required by chart
    - secretKey: bucket
      remoteRef:
        key: supabase/s3
        property: bucket_name
    - secretKey: region
      remoteRef:
        key: supabase/s3
        property: region
{{- end }}
