apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://charts.external-secrets.io
    chart: external-secrets
    targetRevision: 0.16.1
    helm:
      values: |
        # General configuration
        replicaCount: 1
        installCRDs: true
        
        # Resource configuration
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 256Mi
        
        # Security configuration
        securityContext:
          enabled: true
          runAsNonRoot: true
          runAsUser: 1000
          capabilities:
            drop: ["ALL"]
          readOnlyRootFilesystem: true
        
        # Service account configuration
        serviceAccount:
          create: true
          name: external-secrets
          annotations:
            eks.amazonaws.com/role-arn: arn:aws:iam::851725652296:role/supabase-on-eks-external-secrets-20250918044322522300000006
        
        # Logging configuration
        log:
          level: info
        
        # Webhook configuration
        webhook:
          create: true
          certManager:
            enabled: false
        
        # Certificate controller configuration
        certController:
          create: true
        
        # Metrics configuration
        metrics:
          service:
            enabled: true
  
  destination:
    server: https://kubernetes.default.svc
    namespace: external-secrets
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
