apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: supabase-network-policies
  namespace: argocd
  labels:
    app.kubernetes.io/name: supabase-network-policies
spec:
  project: default
  source:
    repoURL: https://github.com/JesusPaz/supabase-on-eks-cdktf.git
    path: k8s/networking/policies
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: supabase
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
  revisionHistoryLimit: 3
