apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: supabase
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/jesuspaz/supabase-on-eks-cdktf
    path: helm/supabase
    targetRevision: HEAD  # Use main branch
    helm:
      valueFiles:
        - values-aws.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: supabase
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
