---
# Database credentials from RDS
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: supabase-db-secret
  namespace: supabase
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretsmanager
    kind: ClusterSecretStore
  target:
    name: supabase-db-secret
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: supabase/database
        property: username
    - secretKey: password
      remoteRef:
        key: supabase/database
        property: password
    - secretKey: database
      remoteRef:
        key: supabase/database
        property: database

---
# JWT secrets
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: supabase-jwt-secret
  namespace: supabase
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretsmanager
    kind: ClusterSecretStore
  target:
    name: supabase-jwt-secret
    creationPolicy: Owner
  data:
    - secretKey: jwt-secret
      remoteRef:
        key: supabase/jwt
        property: secret
    - secretKey: anon-key
      remoteRef:
        key: supabase/jwt
        property: anon_key
    - secretKey: service-key
      remoteRef:
        key: supabase/jwt
        property: service_role_key

---
# Analytics secret
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: supabase-analytics-secret
  namespace: supabase
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretsmanager
    kind: ClusterSecretStore
  target:
    name: supabase-analytics-secret
    creationPolicy: Owner
  data:
    - secretKey: api-key
      remoteRef:
        key: supabase/analytics
        property: logflare_api_key

---
# Dashboard credentials
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: supabase-dashboard-secret
  namespace: supabase
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretsmanager
    kind: ClusterSecretStore
  target:
    name: supabase-dashboard-secret
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: supabase/dashboard
        property: username
    - secretKey: password
      remoteRef:
        key: supabase/dashboard
        property: password

---
# S3 Storage credentials
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: supabase-s3-secret
  namespace: supabase
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretsmanager
    kind: ClusterSecretStore
  target:
    name: supabase-s3-secret
    creationPolicy: Owner
  data:
    - secretKey: bucket-name
      remoteRef:
        key: supabase/s3
        property: bucket_name
    - secretKey: region
      remoteRef:
        key: supabase/s3
        property: region
    - secretKey: access-key-id
      remoteRef:
        key: supabase/s3
        property: access_key_id  # Not used with IRSA but required by chart
    - secretKey: secret-access-key
      remoteRef:
        key: supabase/s3
        property: secret_access_key  # Not used with IRSA but required by chart
