apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: supabase
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/supabase-community/supabase-kubernetes
    path: charts/supabase
    targetRevision: HEAD  # Use latest from main branch
    helm:
      values: |
        # Security configuration - Using External Secrets from AWS Secrets Manager
        secret:
          jwt:
            # These will be populated by External Secrets
            secretRef: "supabase-jwt-secret"
            secretRefKey:
              anonKey: "anon-key"
              serviceKey: "service-key"
              secret: "jwt-secret"
          db:
            # These will be populated by External Secrets
            secretRef: "supabase-db-secret"
            secretRefKey:
              username: "username"
              password: "password"
              database: "database"
          analytics:
            # This will be populated by External Secrets
            secretRef: "supabase-analytics-secret"
            secretRefKey:
              apiKey: "api-key"
          dashboard:
            # These will be populated by External Secrets
            secretRef: "supabase-dashboard-secret"
            secretRefKey:
              username: "username"
              password: "password"
          s3:
            # S3 access via IRSA (no keys needed)
            secretRef: "supabase-s3-secret"
            secretRefKey:
              keyId: "access-key-id"  # Not used with IRSA
              accessKey: "secret-access-key"  # Not used with IRSA
        
        # Database configuration (External RDS)
        db:
          enabled: false  # Using external RDS PostgreSQL
          # External database connection will be handled by External Secrets
        
        # Studio configuration
        studio:
          enabled: true
          replicaCount: 1
          environment:
            SUPABASE_PUBLIC_URL: "https://supabase.stack-ai.jesuspaz.com"
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 256Mi
          autoscaling:
            enabled: true
            minReplicas: 1
            maxReplicas: 3
            targetCPUUtilizationPercentage: 80
        
        # Auth service configuration
        auth:
          enabled: true
          replicaCount: 1
          image:
            repository: supabase/gotrue
            tag: "v2.179.0"
            pullPolicy: IfNotPresent
          environment:
            DB_PORT: "5432"
            DB_DRIVER: "postgres"
            DB_SSL: "disable"
            API_EXTERNAL_URL: "https://supabase.stack-ai.jesuspaz.com"
            GOTRUE_SITE_URL: "https://supabase.stack-ai.jesuspaz.com"
          env:
            # Database connection from External Secrets
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: supabase-db-secret
                  key: host
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: supabase-db-secret
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: supabase-db-secret
                  key: password
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: supabase-db-secret
                  key: database
            # JWT secrets from External Secrets
            - name: GOTRUE_JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: supabase-jwt-secret
                  key: jwt-secret
            - name: GOTRUE_JWT_ANON_KEY
              valueFrom:
                secretKeyRef:
                  name: supabase-jwt-secret
                  key: anon-key
            - name: GOTRUE_JWT_SERVICE_KEY
              valueFrom:
                secretKeyRef:
                  name: supabase-jwt-secret
                  key: service-key
          resources:
            requests:
              cpu: 200m
              memory: 256Mi
            limits:
              cpu: 1000m
              memory: 512Mi
          autoscaling:
            enabled: true
            minReplicas: 2
            maxReplicas: 10
            targetCPUUtilizationPercentage: 70
        
        # REST API (PostgREST) configuration
        rest:
          enabled: true
          replicaCount: 2
          resources:
            requests:
              cpu: 200m
              memory: 256Mi
            limits:
              cpu: 1000m
              memory: 512Mi
          autoscaling:
            enabled: true
            minReplicas: 2
            maxReplicas: 15
            targetCPUUtilizationPercentage: 70
        
        # Realtime service configuration
        realtime:
          enabled: true
          replicaCount: 2
          resources:
            requests:
              cpu: 200m
              memory: 256Mi
            limits:
              cpu: 1000m
              memory: 512Mi
          autoscaling:
            enabled: true
            minReplicas: 2
            maxReplicas: 8
            targetCPUUtilizationPercentage: 70
        
        # Meta service configuration
        meta:
          enabled: true
          replicaCount: 1
          image:
            repository: supabase/postgres-meta
            tag: "v0.91.6"
            pullPolicy: IfNotPresent
          environment:
            # Database connection configuration
            PG_META_PORT: "8080"
            DB_PORT: "5432"
            DB_DRIVER: "postgres"
            DB_SSL: "disable"
          env:
            # Database connection from External Secrets
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: supabase-db-secret
                  key: host
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: supabase-db-secret
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: supabase-db-secret
                  key: password
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: supabase-db-secret
                  key: database
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 256Mi
          autoscaling:
            enabled: true
            minReplicas: 1
            maxReplicas: 3
            targetCPUUtilizationPercentage: 80
        
        # Storage service configuration (S3 backend)
        storage:
          enabled: true
          replicaCount: 2
          environment:
            STORAGE_BACKEND: s3
            AWS_DEFAULT_REGION: us-east-1
            GLOBAL_S3_PROTOCOL: https
            GLOBAL_S3_FORCE_PATH_STYLE: false
          serviceAccount:
            create: true
            name: supabase-storage
            annotations:
              eks.amazonaws.com/role-arn: "arn:aws:iam::851725652296:role/supabase-on-eks-app-s3-20250918044322522300000007"
          persistence:
            enabled: false  # Using S3, not local storage
          resources:
            requests:
              cpu: 200m
              memory: 256Mi
            limits:
              cpu: 1000m
              memory: 512Mi
          autoscaling:
            enabled: true
            minReplicas: 2
            maxReplicas: 6
            targetCPUUtilizationPercentage: 70
        
        # Image Proxy configuration
        imgproxy:
          enabled: true
          replicaCount: 1
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 256Mi
          autoscaling:
            enabled: true
            minReplicas: 1
            maxReplicas: 3
            targetCPUUtilizationPercentage: 80
        
        # Kong Gateway configuration
        kong:
          enabled: true
          replicaCount: 2
          ingress:
            enabled: true
            className: "alb"
            annotations:
              kubernetes.io/ingress.class: alb
              alb.ingress.kubernetes.io/scheme: internet-facing
              alb.ingress.kubernetes.io/target-type: ip
              alb.ingress.kubernetes.io/group.name: production
              alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80},{"HTTPS":443}]'
              alb.ingress.kubernetes.io/ssl-redirect: '443'
              alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:us-east-1:851725652296:certificate/448e98db-b7cd-4efb-b8d0-94bdf6fb2c6a
              alb.ingress.kubernetes.io/subnets: subnet-0f3b48174c8c02281,subnet-0e0a131d3c91fd408,subnet-041db689b2eec84e7
            hosts:
              - host: supabase.stack-ai.jesuspaz.com
                paths:
                  - path: /
                    pathType: Prefix
          resources:
            requests:
              cpu: 200m
              memory: 256Mi
            limits:
              cpu: 1000m
              memory: 512Mi
          autoscaling:
            enabled: true
            minReplicas: 2
            maxReplicas: 5
            targetCPUUtilizationPercentage: 70
        
        # Analytics configuration
        analytics:
          enabled: true
          replicaCount: 1
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 256Mi
          autoscaling:
            enabled: true
            minReplicas: 1
            maxReplicas: 3
            targetCPUUtilizationPercentage: 80
        
        # Vector configuration
        vector:
          enabled: true
          replicaCount: 1
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 300m
              memory: 256Mi
          autoscaling:
            enabled: true
            minReplicas: 1
            maxReplicas: 2
            targetCPUUtilizationPercentage: 80
        
        # Functions configuration
        functions:
          enabled: true
          replicaCount: 1
          image:
            repository: supabase/edge-runtime
            tag: "v1.58.2"  # Specific version tag
            pullPolicy: IfNotPresent
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 256Mi
          autoscaling:
            enabled: true
            minReplicas: 1
            maxReplicas: 5
            targetCPUUtilizationPercentage: 80
        
        # Image Proxy configuration
        imgproxy:
          enabled: true
          replicaCount: 1
          persistence:
            enabled: false  # Imgproxy doesn't need persistent storage
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 256Mi
          autoscaling:
            enabled: true
            minReplicas: 1
            maxReplicas: 3
            targetCPUUtilizationPercentage: 80
        
        # Minio configuration (disabled - using S3)
        minio:
          enabled: false

  destination:
    server: https://kubernetes.default.svc
    namespace: supabase
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
