apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-external-database
  namespace: supabase
  labels:
    app.kubernetes.io/name: allow-external-database
spec:
  podSelector: {}  # Apply to all pods in supabase namespace
  policyTypes:
  - Egress
  egress:
  # Allow ALL egress traffic - never restrict outbound
  - to: []
