apiVersion: operator.tigera.io/v1
kind: Installation
metadata:
  name: default
spec:
  # Policy-only mode - keep VPC CNI for dataplane
  cni:
    type: AmazonVPC
  # Disable BGP since we're using VPC CNI
  calicoNetwork:
    bgp: Disabled
    ipPools: []
  # Minimal components for policy enforcement only
  componentResources:
  - componentName: Node
    resourceRequirements:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 500m
        memory: 512Mi
  - componentName: Typha
    resourceRequirements:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 300m
        memory: 256Mi
  # Variant for policy-only
  variant: Calico
  # Disable features we don't need
  flexVolumePath: /usr/libexec/kubernetes/kubelet-plugins/volume/exec/
